# Generated by Django 6.0.1 on 2026-01-09 04:37

import bank.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название валюты')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код валюты')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ валюты')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основная валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_positive', models.BooleanField(default=True, verbose_name='Увеличивает баланс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип транзакции',
                'verbose_name_plural': 'Типы транзакций',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('passport_number', models.CharField(help_text='Номер паспорта в формате: 000000000000-000000000000', max_length=25, validators=[django.core.validators.RegexValidator(message='Введите номер паспорта в формате: 000000000000-000000000000 (12 цифр, дефис, 12 цифр)', regex='^\\d{12}-\\d{12}$')], verbose_name='Паспортные данные')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('display_currency', models.ForeignKey(blank=True, help_text='Валюта, в которой пользователь видит свои счета', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.currency', verbose_name='Валюта отображения')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default=bank.models.generate_account_number, max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('CHECKING', 'Основной (расчетный)'), ('SAVINGS', 'Накопительный'), ('CREDIT', 'Кредитный'), ('TAX', 'Налоговый'), ('DEPOSIT', 'Депозитный')], default='CHECKING', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('PENDING', 'На рассмотрении'), ('FROZEN', 'Заморожен'), ('CLOSED', 'Закрыт')], default='ACTIVE', max_length=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Процентная ставка', max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.currency', verbose_name='Валюта счета')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма')),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Сумма в валюте счета отправителя/получателя', max_digits=20, verbose_name='Сумма в валюте счета')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=10, help_text='Курс обмена при конвертации валют', max_digits=20, null=True, verbose_name='Курс обмена')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=True, verbose_name='Завершена')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='bank.account', verbose_name='Счет отправителя')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='bank.account', verbose_name='Счет получателя')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.transactiontype', verbose_name='Тип транзакции')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))], verbose_name='Курс обмена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный курс')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действует с')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_rates', to='bank.currency', verbose_name='Исходная валюта')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_rates', to='bank.currency', verbose_name='Целевая валюта')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-valid_from'],
                'unique_together': {('from_currency', 'to_currency', 'valid_from')},
            },
        ),
    ]
