# Generated by Django 6.0.1 on 2026-01-09 05:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='interest_rate',
            field=models.DecimalField(decimal_places=5, default=0.0, help_text='Процентная ставка', max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=15, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('1E-15'))], verbose_name='Курс обмена'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=15, max_digits=30, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Курс обмена при конвертации валют', max_digits=30, null=True, verbose_name='Курс обмена'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=15, help_text='Сумма в валюте счета отправителя/получателя', max_digits=30, verbose_name='Сумма в валюте счета'),
        ),
    ]
