# Generated by Django 6.0.1 on 2026-01-09 07:27

import bank.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_account_balance_alter_account_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_name',
            field=models.CharField(blank=True, help_text='Для государственных счетов: название организации или назначение счета', max_length=200, null=True, verbose_name='Название счета'),
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительная информация о счете', null=True, verbose_name='Описание счета'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_government',
            field=models.BooleanField(default=False, help_text='Отметьте, если это государственный или бюджетный счет', verbose_name='Государственный счет'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=bank.models.generate_account_number, help_text='16-значный номер счета. Если оставить пустым, будет сгенерирован автоматически.', max_length=20, unique=True, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Основной (расчетный)'), ('SAVINGS', 'Накопительный'), ('CREDIT', 'Кредитный'), ('TAX', 'Налоговый'), ('DEPOSIT', 'Депозитный'), ('GOVERNMENT', 'Государственный'), ('RESERVE', 'Резервный'), ('TREASURY', 'Казначейский')], default='CHECKING', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец счета'),
        ),
    ]
